package view.reportforms;

import backend.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import data.DataContainer;
import java.text.SimpleDateFormat;

/**
 * This class contains all the code for the view
 */
public class FacultyReportForm extends javax.swing.JFrame {

    public FacultyReportForm(DataContainer data) {
        // Initialize all the components on the form
        initComponents();
        // Retrieve the list from the data model
        ArrayList<Faculty> listOfFaculties = data.getListOfFaculties();

        // Call method that will add all classrooms to the text area
        this.populateTextArea(listOfFaculties);

        // Call method that will add all classrooms to the table
        this.populateTable(listOfFaculties);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOfFaculty = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOfFaculty = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("List Of Faculty At A Glance");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 210, 14);

        textAreaOfFaculty.setColumns(20);
        textAreaOfFaculty.setRows(5);
        jScrollPane1.setViewportView(textAreaOfFaculty);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 45, 720, 124);

        jLabel2.setText("List of Faculty");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 190, 270, 14);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(320, 380, 120, 23);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tableOfFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "SSN", "Status", "Salary", "Date of Birth", "Date of Hire", "Date of Termination"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOfFaculty.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tableOfFaculty);
        tableOfFaculty.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 860, 138);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateTextArea(ArrayList<Faculty> listOfFaculties) {

        // Initialize the string which will hold the data for the text area
        // Start with labels
        String listOfFacultyString = "";

        // Loop through the list and add the faculty names to the text area,
        // Each time adding a cr/lf between items for readibility.
        for (Faculty afaculty : listOfFaculties) {
            listOfFacultyString += afaculty.getName() + "\n";
        }
        // Once all the data is in the string, set the text of the text area to the string value
        textAreaOfFaculty.setText(listOfFacultyString);
 
    }

    /**
     * Private method that will add all classrooms to the table
     */
    private void populateTable(ArrayList<Faculty> listOfFaculties) {

        // A table model like this will hold the data for the JTable (this is the M in MVC)
        DefaultTableModel defaultTableModel = new DefaultTableModel();

        // add columns to table model
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("Address");
        defaultTableModel.addColumn("SSN");
        defaultTableModel.addColumn("Status");
        defaultTableModel.addColumn("Salary");
        defaultTableModel.addColumn("Date of Birth");
        defaultTableModel.addColumn("Date of Hire");
        defaultTableModel.addColumn("Date of Termination");
        
        // Link the data model to the table
        tableOfFaculty.setModel(defaultTableModel);

        // Add the classrooms in the ArrayList to the table model
        for (Faculty aFaculty : listOfFaculties) {

            // Create a vector that is one row in the table
            Vector tableRow = new Vector();

            // Add the data to the vector
            tableRow.add(aFaculty.getName());
            tableRow.add(aFaculty.getAddress());
            tableRow.add(aFaculty.getSocialSecurityNumber());
            tableRow.add(aFaculty.getStatus());
            tableRow.add(aFaculty.getSalary());
         
            // Format the dates using a SimpleDateFormat object
            SimpleDateFormat dateformatter = new SimpleDateFormat("MM/dd/yyyy");
            String stringdate = dateformatter.format(aFaculty.getDateOfBirth().getTime());
            tableRow.add(stringdate);
            stringdate = dateformatter.format(aFaculty.getDateOfHire().getTime());
            tableRow.add(stringdate);
            stringdate = dateformatter.format(aFaculty.getDateOfTermination().getTime());
            tableRow.add(stringdate);
             // Add the vector to the  data model that is connected to the JTable
            defaultTableModel.addRow(tableRow);
        }
    }
private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_closeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableOfFaculty;
    private javax.swing.JTextArea textAreaOfFaculty;
    // End of variables declaration//GEN-END:variables
}
