package view.reportforms;



import backend.OfferedCourse;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import data.DataContainer;
/**
 * This class contains all the code for the view
 */
public class OfferedCourseReportForm extends javax.swing.JFrame {

    public OfferedCourseReportForm(DataContainer data) {
        // Initialize all the components on the form
        initComponents();  
                // Retrieve the list from the data model
        ArrayList<OfferedCourse> listOfOfferedCourses = data.getListOfClassBases();
        
        // Call method that will add all offered courses to the text area
        this.populateTextArea(listOfOfferedCourses);
        // Call method that will add all offered courses to the table
        this.populateTable(listOfOfferedCourses);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCourseTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOfAvailableCourses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("List Of Available Courses At A Glance");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(275, 20, 210, 14);

        listCourseTextArea.setColumns(20);
        listCourseTextArea.setRows(5);
        jScrollPane1.setViewportView(listCourseTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 45, 720, 124);

        jLabel2.setText("Tabular List of Available Courses");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 190, 300, 14);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(310, 380, 120, 23);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tableOfAvailableCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Classroom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOfAvailableCourses.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tableOfAvailableCourses);
        tableOfAvailableCourses.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableOfAvailableCourses.getColumnModel().getColumn(0).setResizable(false);
        tableOfAvailableCourses.getColumnModel().getColumn(1).setResizable(false);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 720, 138);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Private method that will add all classrooms to the text area
     */
    private void populateTextArea(ArrayList<OfferedCourse> listOfOfferedCourses) {

        // Initialize the string which will hold the data for the text area
        // Start with labels
        String allCourseText = "";

        // Loop through the list and add the courses to the text area,
        // Each time adding a cr/lf between items for readibility.
        for (int i = 0; i < listOfOfferedCourses.size(); i++) {
            OfferedCourse aCourse = listOfOfferedCourses.get(i);
            String courseId = aCourse.getCourseId();
            String courseName = aCourse.getCourseName();
            allCourseText += courseId;
            allCourseText += " ";
            allCourseText += courseName;
            allCourseText += "\n";            
        }
        // Once all the data is in the string, set the text of the text area to the string value
        listCourseTextArea.setText(allCourseText);
    }

    /**
     * Private method that will add all classrooms to the table
     */
    private void populateTable(ArrayList<OfferedCourse> listOfOfferedCourses) {

        // A table model like this will hold the data for the JTable (this is the M in MVC)
        DefaultTableModel defaultTableModel = new DefaultTableModel();

        // add columns to table model
        defaultTableModel.addColumn("Course Number");
        defaultTableModel.addColumn("Course Name");
        defaultTableModel.addColumn("Classroom");

        // Link the data model to the table
        tableOfAvailableCourses.setModel(defaultTableModel);

        // Add the classrooms in the ArrayList to the table model
        for (OfferedCourse aCourse : listOfOfferedCourses) {

            // Create a vector that is one row in the table
            Vector aClassroomForTable = new Vector();

            // Add the data to the vector
            aClassroomForTable.add(aCourse.getCourseId());
            aClassroomForTable.add(aCourse.getCourseName());
            aClassroomForTable.add(aCourse.getClassroom().getRoomNumber());

            // Add the vector to the  data model that is connected to the JTable
            defaultTableModel.addRow(aClassroomForTable);
        }
    }
private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea listCourseTextArea;
    private javax.swing.JTable tableOfAvailableCourses;
    // End of variables declaration//GEN-END:variables
}
