/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import backend.Faculty;
import backend.OfferedCourse;
import backend.Student;
import backend.StudentCourse;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hoang Nguyen
 */
public class NewStudentCourseAddForm extends javax.swing.JFrame {

    // Data model used for the list of courses on the form.  This list will be
    // used to assign courses to a student
    private DefaultListModel listModel = new DefaultListModel();

    // New Student just created
    private Student newStudent;

    /**
     * Creates new form NewStudent CourseAddForm
     */
    public NewStudentCourseAddForm(Student newStudent, ArrayList<OfferedCourse> listOfAvailableCourses) {
        initComponents();

        this.newStudent = newStudent;

        // Store the courses in the list
        // If there are any courses available, add them to the data model for 
        // the list on the form
        for (int i = 0; i < listOfAvailableCourses.size(); i++) {
            listModel.addElement(listOfAvailableCourses.get(i).getCourseId());
        }

        // Link the data model to the list on the form
        courseList.setModel(listModel);
        
        this.setSize(700,500);

    }

    NewStudentCourseAddForm(Faculty newFaculty, ArrayList<OfferedCourse> listOfAvailableCourses) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gradesListField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Student Course Add");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 340, 14);

        saveButton.setText("Add Course");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(480, 40, 125, 23);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(480, 70, 125, 23);

        courseList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(courseList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(18, 43, 450, 250);

        jLabel2.setText("Enter comma separated list of grades:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 300, 330, 14);

        gradesListField.setColumns(1);
        gradesListField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gradesListField.setRows(5);
        jScrollPane2.setViewportView(gradesListField);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 320, 450, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Retrieve selected course from the list and create StudentyCourse object
        // Note that the courses are stored as generic objects and will be converted as they are used
        String courseid = (String) this.courseList.getSelectedValue();

        // Retrieve the course list from the student object
        ArrayList<StudentCourse> listofStudentCourses = this.newStudent.getEnrolledCourses();

        // Create a new student course and set its values
        StudentCourse studentcourse = new StudentCourse();
        
        // Set the course id
        studentcourse.setCourseId(courseid);
        
        // Parse the list of grades and store in the student course object
        // (Convert from strings to floats)
        String[] grades = this.gradesListField.getText().split(",");
        for (String grade : grades) {
            studentcourse.getCourseGrades().add(Float.parseFloat(grade));
        }
        
        // Store the course
        listofStudentCourses.add(studentcourse);
        
        // Clear the grades
        this.gradesListField.setText("");

    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JList courseList;
    private javax.swing.JTextArea gradesListField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
