/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * TopLevelMenuForm.java
 *
 * Created on Jun 10, 2017, 5:15:42 PM
 */
package view.menus;

import java.awt.event.ActionListener;
import data.DataContainer;
import view.InputClassroomForm;
import view.reportforms.ClassroomListReport;
import view.InputOfferedCourseForm;
import view.reportforms.OfferedCourseReportForm;
import view.InputStudentInfo;
import view.reportforms.StudentReportForm;
import view.InputFacultyForm;
import view.reportforms.FacultyReportForm;

/**
 * @author Hoang Nguyen
 */
public class TopLevelMenuForm extends javax.swing.JFrame implements ActionListener {

// This is the data model that will get passed to all forms. 
    DataContainer datamodel = new DataContainer();

    /**
     * Creates new form TopLevelMenuForm
     */
    public TopLevelMenuForm() {
        initComponents();
        // Link the menu items to the actionPerformed method in this class
        this.addClassroom.addActionListener(this);
        this.listclassrooms.addActionListener(this);
        this.addCourse.addActionListener(this);
        this.courseList.addActionListener(this);
        this.addStudent.addActionListener(this);
        this.studentLists.addActionListener(this);
        this.addFaculty.addActionListener(this);
        this.facultyList.addActionListener(this);
        this.saveMenuItem.addActionListener(this);
        this.exitMenu.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        addClassroom = new javax.swing.JMenuItem();
        listclassrooms = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        addCourse = new javax.swing.JMenuItem();
        courseList = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        addStudent = new javax.swing.JMenuItem();
        studentLists = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        addFaculty = new javax.swing.JMenuItem();
        facultyList = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu2.add(exitMenu);

        saveMenuItem.setText("Save Data");
        jMenu2.add(saveMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Classroom");

        addClassroom.setText("Add Classroom");
        jMenu5.add(addClassroom);

        listclassrooms.setText("List Classrooms");
        jMenu5.add(listclassrooms);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Courses");

        addCourse.setText("Add Course");
        jMenu7.add(addCourse);

        courseList.setText("List Courses");
        jMenu7.add(courseList);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Students");

        addStudent.setText("Add Student");
        jMenu8.add(addStudent);

        studentLists.setText("List Students");
        jMenu8.add(studentLists);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Faculty");

        addFaculty.setText("Add Faculty");
        jMenu9.add(addFaculty);

        facultyList.setText("List Faculty");
        jMenu9.add(facultyList);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_exitMenuActionPerformed
    /**
     * ActionListener actionPerformed method implemented
     */
    @Override
    public void actionPerformed(java.awt.event.ActionEvent event) {

        //  Figure out which button was clicked
        String menuItemClicked = event.getActionCommand();
        //Link to add classroom form and list classroom
        if (menuItemClicked.equals("List Classrooms")) {
            ClassroomListReport listClassroomForm = new ClassroomListReport(datamodel);
            listClassroomForm.setSize(800, 450);
            listClassroomForm.setVisible(true);
        } else if (menuItemClicked.equals("Add Classroom")) {
            InputClassroomForm addClassroomForm = new InputClassroomForm(datamodel);
            addClassroomForm.setVisible(true);
        } else if (menuItemClicked.equals("Save Data")) {
            datamodel.writeSerializedFile();
            datamodel.writeTextFile();
            datamodel.writeXML();
        } // Link to add course and course list form
        else if (menuItemClicked.equals("Add Course")) {
            InputOfferedCourseForm addOfferedCourseForm = new InputOfferedCourseForm(datamodel);
            addOfferedCourseForm.setVisible(true);
        } else if (menuItemClicked.equals("List Courses")) {
            OfferedCourseReportForm listOfferedForm = new OfferedCourseReportForm(datamodel);
            listOfferedForm.setSize(800, 450);
            listOfferedForm.setVisible(true);
        } // Link to add student and student list form
        else if (menuItemClicked.equals("List Students")) {
            StudentReportForm listStudentForm = new StudentReportForm(datamodel);
            listStudentForm.setSize(800, 450);
            listStudentForm.setVisible(true);
        } else if (menuItemClicked.equals("Add Student")) {
            InputStudentInfo addStudentForm = new InputStudentInfo(datamodel);
            addStudentForm.setVisible(true);
        }
    // Link to add faculty and faculty form

    else if (menuItemClicked.equals ( 
        "List Faculty")) 
        {
            FacultyReportForm listFacultyForm = new FacultyReportForm(datamodel);
        listFacultyForm.setSize(800, 650);
        listFacultyForm.setVisible(true);
    }

    else if (menuItemClicked.equals ( 
        "Add Faculty")) {
            InputFacultyForm addFacultyForm = new InputFacultyForm(datamodel);
        addFacultyForm.setVisible(true);
    }
}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
        public void run() {
                new TopLevelMenuForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addClassroom;
    private javax.swing.JMenuItem addCourse;
    private javax.swing.JMenuItem addFaculty;
    private javax.swing.JMenuItem addStudent;
    private javax.swing.JMenuItem courseList;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem facultyList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem listclassrooms;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem studentLists;
    // End of variables declaration//GEN-END:variables
}
